//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSS_Form1.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regra
    {
        public int regra_codigo { get; set; }
        public string regra_chaves { get; set; }
        public Nullable<bool> regra_ativo { get; set; }
        public string regra_tipo { get; set; }
    }
}
